server:
  port: 8080   # Change port if needed

spring:
  application:
    name: untitled2  # App name

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG  # Logs SQL statements

app:
  security:
    clients:
      - id: test_client_jiffy_001
        secret: mock_secret_abc123xyz789_jiffy_test
        name: Jiffy Test Client
        status: Active
      - id: demo_client_jiffy_002
        secret: mock_secret_demo456def789_jiffy_integration
        name: Jiffy Demo Client
        status: Active
