server: # (need this in jiffy)
  port: 8081   # Change port if needed

spring:
  application:
    name: untitled2  # App name

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/jiffy-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  realm: http://localhost:8080/realms/jiffy-realm
  realm-admin-api: http://localhost:8080/admin/realms/jiffy-realm
  client: jiffy-dev-app
  admin-username: jiffyuser     # Keycloak admin user
  admin-password: jiffyuser

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG  # Logs SQL statements
    org:
      springframework:
        security: DEBUG
        security.oauth2: DEBUG

app:   # (need this in jiffy)
  security:
    clients:
      - id: test_client_jiffy_001
        secret: mock_secret_abc123xyz789_jiffy_test
        name: Jiffy Test Client
        status: Active
      - id: demo_client_jiffy_002
        secret: mock_secret_demo456def789_jiffy_integration
        name: Jiffy Demo Client
        status: Active

jwt: # (need this in jiffy)
  auth:
    converter:
      principle-attribute: preferred_username
      role: role

      # For realm based role access
      realm-access: realm_access

      # For client based role access
      resource-access: resource_access
      resource-id: jiffy-dev-app



